landing_homepage:
    path:     /
    defaults: { _controller: LandingBundle:Default:index }

producto:
    path:     /producto/{numero}
    defaults: { _controller: LandingBundle:Default:producto }

